# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9635a4280e6f6f60e04a9c8e356ac160b7cc5bec2c6be2e83d035309a9b58e4efb9ce2ac855f6193aeb9f007714e0fcfb6db12f9d5dae03bf79b57036699fb4

test:
  secret_key_base: 18a75de04ab9595527c88d489b9cbcbeb6ccc574dd6b675e9407d57fd28c436df557bc151b4e1169c3284ac1c96be8eea2c5c666c3780665872916a326a3ba34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
